version: 2

builds:
  - main: ./cmd/autopr
    binary: ap
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X autopr/cmd/autopr/cli.version={{.Version}}
      - -X autopr/cmd/autopr/cli.commit={{.ShortCommit}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

# NOTE: Current CI uses `goreleaser build` only. These blocks are kept in case we
# switch back to `goreleaser release` later.
archives:
  - formats:
      - tar.gz
    name_template: "ap_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"

release:
  github:
    owner: ashwath-ramesh
    name: autopr
